import { useMemo } from 'react';
import { useGame } from './useGame';
import { SoleNetPost, SoleNetDm } from '../types/social';
import { SOLE_NET_NPCS } from '../data/soleNetNpcs';
import { SOLE_NET_CELEBRITIES } from '../data/soleNetCelebrities';
import { SNEAKERS } from '../data/sneakers';
import { CITIES } from '../data/cities';
import { rngFor, sampleWithout } from '../utils/rng';

/**
 * SoleNet, made reproducible.
 *
 * The feed was thirty independent `Math.random()` draws from small pools,
 * regenerated by a `useMemo` that dies with the screen. Two consequences, both
 * visible the moment you actually scrolled it:
 *
 *   - **It repeated itself.** Measured on a live page: six of twenty-nine
 *     posts were exact duplicates of another post on the same screen. That is
 *     the birthday problem doing what it always does — drawing independently
 *     from a pool of a few dozen lines collides long before it runs out.
 *   - **It rerolled every visit.** Leave the feed and come straight back on
 *     the same day, in the same city, and only one of the top eight posts
 *     survived. Every other generated system in this game (the shelf, the npc
 *     schedule, the hype calendar) is seeded precisely so the world holds
 *     still long enough to be read; the feed was the one that did not, so its
 *     rumours were worth nothing to a player trying to act on them.
 *
 * Now seeded on day + city like everything else, and drawn without
 * replacement per author so one voice cannot say the same thing twice.
 */

/** One draw from a pool, via the seeded stream. */
const pickFrom = <T>(arr: readonly T[], rng: () => number): T => arr[Math.floor(rng() * arr.length)];

// Helper to populate template strings, if they are templates
const populateTemplate = (template: string, sneaker: (typeof SNEAKERS)[0], city: (typeof CITIES)[0]): string => {
    if (!template.includes('{')) {
        return template; // It's not a template, return as is
    }
    return template
        .replace('{sneaker_name}', sneaker.name)
        .replace('{sneaker_rarity}', sneaker.rarity)
        .replace('{city_name}', city.name);
};

const ALL_AUTHORS = [...SOLE_NET_NPCS, ...SOLE_NET_CELEBRITIES];

export function useSoleNet(postCount: number = 30, dmCount: number = 10) {
    const { gameState } = useGame();
    const { day, currentCityId } = gameState;
    const currentCity = CITIES.find(c => c.id === currentCityId)!;

    const { posts, dms } = useMemo(() => {
        // Timestamps are relative to a fixed point for the day rather than to
        // `Date.now()`, or the sort order drifts on every render and posts
        // reshuffle while you are reading them.
        const dayStart = Date.UTC(2024, 0, 1) + day * 86400000;

        const generatedPosts: SoleNetPost[] = [];
        const generatedDms: SoleNetDm[] = [];
        
        const rng = rngFor(`solenet-${currentCityId}-day${day}`);

        // Lines already used, per author. A pool is small enough that two
        // independent draws collide often, so each author's next post is
        // chosen from what they have not already said on this screen.
        const usedBy = new Map<string, Set<string>>();
        const freshLine = (authorId: string, pool: readonly string[]): string | null => {
            const used = usedBy.get(authorId) ?? new Set<string>();
            const left = pool.filter(line => !used.has(line));
            if (left.length === 0) return null;
            const line = pickFrom(left, rng);
            used.add(line);
            usedBy.set(authorId, used);
            return line;
        };

        // --- Generate Posts ---
        for (let i = 0; i < postCount; i++) {
            const author = pickFrom(ALL_AUTHORS, rng);
            const sneaker = pickFrom(SNEAKERS, rng);
            let contentPool: string[] = [];
            let type: SoleNetPost['type'] = 'chatter';

            const rand = rng();
            if (author.type === 'insider' && author.messagePool.rumors.length > 0 && rand < 0.8) {
                contentPool = author.messagePool.rumors;
                type = 'rumor';
            } else if (author.type === 'bot' && rand < 0.9) {
                contentPool = author.messagePool.chatter;
                type = 'ad';
            } else {
                 contentPool = author.messagePool.chatter;
                 if (author.type === 'chaos-agent') type = 'chaos';
                 // Celebrities are often influencers but post chaotic content
                 if (['donald-drip', 'bro-jogan'].includes(author.id)) type = 'chatter';
            }

            const line = contentPool.length > 0 ? freshLine(author.id, contentPool) : null;
            // An author with nothing left to say is skipped rather than made
            // to repeat themselves — a slightly shorter feed beats a feed that
            // stutters.
            if (line !== null) {
                 generatedPosts.push({
                    id: `post-${day}-${i}`,
                    author,
                    content: populateTemplate(line, sneaker, currentCity),
                    type,
                    likes: Math.floor(rng() * 500),
                    reposts: Math.floor(rng() * 100),
                    timestamp: dayStart - Math.floor(rng() * 1000 * 60 * 60 * 8), // Within last 8 hours
                });
            }
        }

        // --- Generate DMs ---
        const dmSenders = ALL_AUTHORS.filter(npc => npc.messagePool.dms.length > 0);
        // One thread per sender: a DM list with the same person twice, each
        // opening a conversation from scratch, reads as a bug rather than as a
        // busy inbox.
        const chosen = sampleWithout(dmSenders, dmCount, rng);
        for (let i = 0; i < chosen.length; i++) {
            const sender = chosen[i];
            const sneaker = pickFrom(SNEAKERS, rng);
            let type: SoleNetDm['type'] = 'flavor';
            
            if (sender.type === 'insider') type = 'tip';
            if (sender.type === 'bot') type = 'scam';

            if (sender) {
                generatedDms.push({
                    id: `dm-${day}-${i}`,
                    sender,
                    messages: [{ text: populateTemplate(pickFrom(sender.messagePool.dms, rng), sneaker, currentCity), isPlayer: false }],
                    type,
                    isRead: rng() > 0.5,
                    timestamp: dayStart - Math.floor(rng() * 1000 * 60 * 60 * 24 * 3), // Within last 3 days
                });
            }
        }


        return { 
            posts: generatedPosts.sort((a, b) => b.timestamp - a.timestamp),
            dms: generatedDms.sort((a, b) => b.timestamp - a.timestamp)
        };

    }, [day, currentCityId, postCount, dmCount, currentCity]);

    return { posts, dms };
}
